# Generated by Django 5.0 on 2023-12-12 20:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('religion', models.CharField(blank=True, default='Católica', max_length=30, null=True, verbose_name='Religião')),
                ('race', models.CharField(blank=True, choices=[('B', 'Branca'), ('P', 'Preta'), ('PA', 'Parda'), ('A', 'Amarela'), ('I', 'Indígena')], max_length=2, null=True, verbose_name='Cor/Raça/Etnia')),
                ('nationality', models.CharField(blank=True, default='Brasileiro(a)', max_length=30, null=True, verbose_name='Nacionalidade')),
                ('crm', models.CharField(max_length=11, unique=True, verbose_name='CRM nº')),
                ('rqe', models.CharField(max_length=11, unique=True, verbose_name='RQE nº')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Médico(a)',
                'verbose_name_plural': 'Médicos',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('religion', models.CharField(blank=True, default='Católica', max_length=30, null=True, verbose_name='Religião')),
                ('race', models.CharField(blank=True, choices=[('B', 'Branca'), ('P', 'Preta'), ('PA', 'Parda'), ('A', 'Amarela'), ('I', 'Indígena')], max_length=2, null=True, verbose_name='Cor/Raça/Etnia')),
                ('nationality', models.CharField(blank=True, default='Brasileiro(a)', max_length=30, null=True, verbose_name='Nacionalidade')),
                ('relationship', models.CharField(choices=[('M', 'Mãe'), ('P', 'Pai'), ('R', 'Responsável')], max_length=1, verbose_name='Grau de Parentesco')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.relative', verbose_name='Cônjuge')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('religion', models.CharField(blank=True, default='Católica', max_length=30, null=True, verbose_name='Religião')),
                ('race', models.CharField(blank=True, choices=[('B', 'Branca'), ('P', 'Preta'), ('PA', 'Parda'), ('A', 'Amarela'), ('I', 'Indígena')], max_length=2, null=True, verbose_name='Cor/Raça/Etnia')),
                ('nationality', models.CharField(blank=True, default='Brasileiro(a)', max_length=30, null=True, verbose_name='Nacionalidade')),
                ('allergy', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('family_history', models.TextField(blank=True, null=True, verbose_name='História Familiar')),
                ('personal_history', models.TextField(blank=True, null=True, verbose_name='História Pessoal')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='profiles.medic', verbose_name='Médico(a)')),
                ('relative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatives', to='profiles.relative', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Nascimento')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('religion', models.CharField(blank=True, default='Católica', max_length=30, null=True, verbose_name='Religião')),
                ('race', models.CharField(blank=True, choices=[('B', 'Branca'), ('P', 'Preta'), ('PA', 'Parda'), ('A', 'Amarela'), ('I', 'Indígena')], max_length=2, null=True, verbose_name='Cor/Raça/Etnia')),
                ('nationality', models.CharField(blank=True, default='Brasileiro(a)', max_length=30, null=True, verbose_name='Nacionalidade')),
                ('enter_date', models.DateField(default=datetime.date.today, verbose_name='Data de entrada')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Secretária',
                'verbose_name_plural': 'Secretárias',
            },
        ),
    ]
