# Generated by Django 5.0 on 2023-12-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Apenas Números', max_length=11, null=True, verbose_name='Telefone'),
        ),
    ]
