# Generated by Django 5.0 on 2023-12-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('schedule_date', models.DateTimeField(verbose_name='Agendado para')),
                ('next_appointment', models.DateTimeField(blank=True, null=True, verbose_name='Próxima Consulta')),
                ('appointment_type', models.CharField(choices=[('PS', 'Plano de Saúde'), ('PP', 'Particular'), ('CO', 'Cortesia')], max_length=2, verbose_name='Tipo da Consulta')),
                ('is_return_appointment', models.BooleanField(default=False, verbose_name='Consulta de Retorno?')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attending_medic', to='profiles.medic', verbose_name='Médico Atendente')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='profiles.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consulta Médica',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Ativo')),
                ('deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pc', models.FloatField(blank=True, null=True, verbose_name='Perímetro Encefálico(PC)')),
                ('pt', models.FloatField(blank=True, null=True, verbose_name='Perímetro Toráxico(PT)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Altura cm')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso Kg')),
                ('current_disease', models.TextField(blank=True, null=True, verbose_name='História Doença Atual')),
                ('physical_exam', models.TextField(blank=True, default='BEG, ATIVO E REATIVO, ACIANÓTICO, ANICTÉRICO, AFEBRIL, EUPNEICO, CORADO, HIDRATADO.\nACV: RCR 2 T SEM SOPRO\nAR: MV + SEM RA AB: RHA+, SEM VMG, EVACUAÇÕES E DIURESE PRESENTES.\nM: TÍPICOS, PULSOS CHEIOS, TEC<3 S\nPELE: SEM ALTERAÇÕES\nGENITÁLIA: SEM ALTERAÇÕES\nDNPM: ADEQUADO PARA IDADE, SEM SINAIS MENINGEOS.\nPUPILAS ISO E FOTO REAGENTES.\nREFLEXOS ADEQUADOS PARA IDADE.\nORO: NORMAL\nOTO: NORMAL\nOLHO: NORMAL \nVACINAS: OK\nHD: HIGIDO\nCD:\n', null=True, verbose_name='Exame Físico')),
                ('diagnose_hypothesis', models.TextField(blank=True, null=True, verbose_name='Hipótese Diagnóstica')),
                ('conduct', models.TextField(blank=True, null=True, verbose_name='Conduta')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicalrecord', to='appointment.appointment', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-created_on'],
            },
        ),
    ]
