
default_appointment = 'BEG, ATIVO E REATIVO, ACIANÓTICO, ANICTÉRICO, AFEBRIL, EUPNEICO, CORADO, HIDRATADO.\n' \
               'ACV: RCR 2 T SEM SOPRO\nAR: MV + SEM RA AB: RHA+, SEM VMG, EVACUAÇÕES E DIURESE PRESENTES.\n' \
               'M: TÍPICOS, PULSOS CHEIOS, TEC<3 S\nPELE: SEM ALTERAÇÕES\nGENITÁLIA: SEM ALTERAÇÕES\n' \
               'DNPM: ADEQUADO PARA IDADE, SEM SINAIS MENINGEOS.\nPUPILAS ISO E FOTO REAGENTES.\n' \
               'REFLEXOS ADEQUADOS PARA IDADE.\nORO: NORMAL\nOTO: NORMAL\nOLHO: NORMAL \nVACINAS: OK\nHD: HIGIDO\nCD:\n'
